### ISSUE TITLE
Plugin highlights class names

### ISSUE THREAD

**Issue by tofik-mamishov** [leomillon/uuid-generator-plugin#17]
Hi!

Thank you for the plugin!

After I had updated the plugin to version 4.0.0 it started to highlight first 32 characters in a class name:

![image](https://user-images.githubusercontent.com/8829804/91557869-ead00680-e93d-11ea-98b6-2cc5e5802a33.png)

I've tried to invalidate caches and reinstall the plugin, but it still highlights.

IDE: Idea Ultimate 2020.2

**Comment by leomillon** [comment]
Hi @tofik-mamishov !

Thanks for your feedback, it seems that this is matching the UUID pattern without dashes.

I'll have to find a way to avoid these edge-cases while still being to parse any language :/

**Comment by balthasar-architect** [comment]
It also highlights almost all longer method names. I had to deactivate the plugin to be able to continue working.

IntelliJ IDEA 2020.2.1 (Ultimate Edition)

**Comment by leomillon** [comment]
I've just published a new version [`4.0.1`](https://github.com/leomillon/uuid-generator-plugin/releases/tag/4.0.1) with the following new rules to improve the UUID and ULID detection:
- must be all lower or all UPPER case
- UUID chars restriction to HEXA only (`[a-f]`)
- ID must have at least 2 numbers
- Cannot have a `[0-9a-zA-Z]` char just before or just after
- Cannot have a `(` char just after

This should avoid edge-cases detection like the one you got.

Please tell me if there are any other cases where there are still "bad" id detections.

I'm sorry for the inconvenience :/

**Comment by tofik-mamishov** [comment]
I made a quick-check of class/method names. Looks like the problem has gone for them. Thank you!

**Comment by leomillon** [comment]
I'm closing the issue but feel free to re-open it if there are still problems with the new detection system.

Again sorry and thanks a lot for your feedback!

**Comment by ste93cry** [comment]
I still have issues around the codebase in places where I don't expect, for example in a API token in a YAML file. Half of the token is highlighted as a UUID. I suggest to either change the regex to match word boundaries only or to let people disable such feature

**Comment by leomillon** [comment]
Hello @ste93cry !

Thanks for your feedback, it's quite hard to match word boundaries in any language as I don't really know if it's in a string literal token or in a function/class name or anything.

So I'll first add a configuration entry to enable/disable the existing highlight feature and then try to manage a better matcher or a dedicated parser per language (but that will be harder to handle "all languages" and to maintain :/ )

**Comment by leomillon** [comment]
Also @ste93cry could you please paste me a similar code sample (= not with the real API token of course ^^) to reproduce your issue ?

**Comment by ste93cry** [comment]
This is an example of a YAML file that is broken. Imho, specifically talking about this language, matching word boundaries should be fine. I also think that strings not matching the UUID format with dashes should not be considered UUIDs, while instead now they are

```yaml
test: 1275ff80-21d5-4c86-866a-9834358c0a04 # this is fine
test2: '1275ff80-21d5-4c86-866a-9834358c0a04' # this is fine
test3: "1275ff80-21d5-4c86-866a-9834358c0a04" # this is fine
test4: "1275ff8021d54c86866a9834358c0a04" # this is not fine
test5: test_1275ff8021d54c86866a9834358c0a04_test # this is not fine
```

**Comment by leomillon** [comment]
Yes I see...

`test4` is still a valid match though but indeed, it may be better to only match UUID with dashes to ensure the correctness of the highlighted data.

There still might be issues with the ULID format but that shouldn't happen so often.

Ok it should be a good way to fix things to only match UUID with dashes.

**Comment by ste93cry** [comment]
>Ok it should be a good way to fix things to only match UUID with dashes.

I would still like if you provide a way to disable the feature: while some people may find this feature useful I think that there are too many cases to consider to avoid highlighting wrong words

**Comment by leomillon** [comment]
@ste93cry I just published the new `4.1.0` version which includes the following changes:

<b>Changes in version 4.1.0:</b>
<ul>
    <li>Add code highlighting configuration in settings</li>
    <li>Only UUID with dashes are highlighted</li>
    <li>Optimization of the UUID and ULID highlighting algorithm</li>
</ul>

I hope this will suit your needs :)

**Comment by ste93cry** [comment]
Awesome, I will test it in the next days and will report any other issue I (hopefully not) will encounter. In the meanwhile feel free to close again this issue
